In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('cancer patient data sets.csv')
df.head()

,index,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,0,P1,33,1,2,4,5,4,3,2,...,3,4,2,2,3,1,2,3,4,Low
1,1,P10,17,1,3,1,5,3,4,2,...,1,3,7,8,6,2,1,7,2,Medium
2,2,P100,35,1,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
3,3,P1000,37,1,7,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,High
4,4,P101,46,1,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High

In [4]:
df['Level'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [5]:
print('Total columns: ',df.shape[1])
print('Dimensions: ', df.shape)
print('Size: ', df.size)
print('Memory usage: ', df.memory_usage())
print('First 50 records: ')
df.head(50)
print('Last 30 records: ')
df.tail(30)

Total columns:  26
Dimensions:  (1000, 26)
Size:  26000
Memory usage:  Index                        132
index                       8000
Patient Id                  8000
Age                         8000
Gender                      8000
Air Pollution               8000
Alcohol use                 8000
Dust Allergy                8000
OccuPational Hazards        8000
Genetic Risk                8000
chronic Lung Disease        8000
Balanced Diet               8000
Obesity                     8000
Smoking                     8000
Passive Smoker              8000
Chest Pain                  8000
Coughing of Blood           8000
Fatigue                     8000
Weight Loss                 8000
Shortness of Breath         8000
Wheezing                    8000
Swallowing Difficulty       8000
Clubbing of Finger Nails    8000
Frequent Cold               8000
Dry Cough                   8000
Snoring                     8000
Level                       8000
dtype: int64
First 50 records:
Last 30 records:

,index,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
970,970,P972,48,2,6,8,7,7,7,6,...,2,7,6,5,1,9,3,4,2,Medium
971,971,P973,36,2,2,1,5,3,2,3,...,6,7,2,5,8,1,3,2,3,Medium
972,972,P974,31,2,3,2,4,2,3,2,...,4,5,6,5,5,4,6,5,4,Medium
973,973,P975,38,2,1,2,3,4,2,4,...,4,1,2,4,6,5,4,2,5,Medium
974,974,P976,35,1,6,8,7,7,7,6,...,2,7,6,5,1,9,3,4,2,Medium
975,975,P977,44,1,6,7,7,7,7,6,...,5,3,2,7,8,2,4,5,3,High
976,976,P978,33,1,2,4,5,4,3,2,...,3,4,2,2,3,1,2,3,4,Low
977,977,P979,45,1,3,1,4,3,2,3,...,3,2,2,4,2,2,3,4,3,Low
978,978,P98,26,2,8,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
979,979,P980,53,1,3,1,4,2,3,2,...,2,2,3,4,1,5,2,6,2,Low
980,980,P981,35,2,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
981,981,P982,46,1,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
982,982,P983,27,1,6,7,7,7,7,6,...,2,7,6,7,6,7,2,3,1,High
983,983,P984,26,1,3,2,4,2,3,2,...,4,5,6,5,5,4,6,5,4,Medium
984,984,P985,37,1,1,2,3,4,2,4,...,4,1,2,4,6,5,4,2,5,Medium
985,985,P986,28,1,6,7,7,7,7,6,...,5,3,2,7,8,2,4,5,3,High
986,986,P987,19,1,6,8,7,7,7,6,...,9,6,5,7,2,4,3,1,4,High
987,987,P988,29,2,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
988,988,P989,39,2,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
989,989,P99,37,1,7,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,High
990,990,P990,49,1,6,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
991,991,P991,37,1,8,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
992,992,P992,26,2,7,7,7,7,7,6,...,2,7,6,7,6,7,2,3,1,High
993,993,P993,37,2,7,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,High
994,994,P994,33,1,6,7,7,7,7,7,...,8,5,7,6,7,8,7,6,2,High
995,995,P995,44,1,6,7,7,7,7,6,...,5,3,2,7,8,2,4,5,3,High
996,996,P996,37,2,6,8,7,7,7,6,...,9,6,5,7,2,4,3,1,4,High
997,997,P997,25,2,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
998,998,P998,18,2,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
999,999,P999,47,1,6,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High

In [6]:
print('Total number of samples: ', df.shape[0])
print('Total number of columns: ', df.shape[1])

Total number of samples:  1000
Total number of columns:  26

In [7]:
df['Level'].value_counts()

Level
High      365
Medium    332
Low       303
Name: count, dtype: int64

In [8]:
sample = df.loc[550:900, 'Gender':'Coughing of Blood']
sample.to_csv('sample.csv')
sample.describe()

,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,Smoking,Passive Smoker,Chest Pain,Coughing of Blood
count,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000
mean,1.396011,3.988604,4.749288,5.319088,4.974359,4.726496,4.472934,4.615385,4.635328,4.045584,4.333333,4.572650,5.022792
std,0.489765,2.042376,2.622941,1.921504,2.084480,2.112374,1.823257,2.136136,2.112089,2.542929,2.344599,2.258886,2.424764
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,2.000000,2.000000,4.000000,3.000000,3.000000,3.000000,2.000000,3.000000,2.000000,2.000000,3.000000,3.000000
50%,1.000000,4.000000,5.000000,6.000000,5.000000,5.000000,5.000000,5.000000,4.000000,3.000000,4.000000,4.000000,4.000000
75%,2.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
max,2.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,7.000000,8.000000,8.000000,9.000000,9.000000

In [9]:
print('index of Shortness of Breath: ', df.columns.get_loc('Shortness of Breath'))
print('index of Frequent Cold: ', df.columns.get_loc('Frequent Cold'))
sample2 = df.iloc[-20:, 18:23]
sample2.to_csv('sample2.csv')
sample2.describe()

index of Shortness of Breath:  18
index of Frequent Cold:  22

,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold
count,20.000000,20.000000,20.00000,20.00000,20.000000
mean,5.400000,3.650000,3.95000,4.05000,4.650000
std,2.542274,2.621269,2.37254,1.79106,1.496487
min,2.000000,1.000000,1.00000,2.00000,2.000000
25%,3.750000,1.000000,1.75000,2.00000,4.000000
50%,5.000000,2.000000,4.00000,4.00000,4.000000
75%,7.500000,7.000000,6.00000,5.00000,6.000000
max,9.000000,7.000000,8.00000,8.00000,7.000000

In [11]:
sample3 = df.iloc[[110,220,360,440,656,778,202,889]]
avg = sample3['Alcohol use'].mean()
print(avg)

5.625